# Generated by Django 6.0.2 on 2026-03-25 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_project_end_date_project_start_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
    ]
